# Generated by Django 6.0.3 on 2026-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
